export const projects = [
    {
        name: "Hilton Hotel",
        about: "Cooperation and coordinating during project design, providing budget details for the investor and contractor, installing and commissioning of WiFi network, IPTV system, Digital Signage and telephony. ",
        client: "Hotel Hilton Belgrade",
        location: "Belgrade, Serbia",
        surface: "34.000 m²",
        value: "€470.000",
        finished: "March 2018.",
        contractor: "Procodex d.o.o.",
        url: "/pcx-projects/hilton-belgrade.jpg",
    },
    {
        name:"Sun Gardens Resort", 
        about: "Installing and commissioning of new IPTV infotainment system. Integrating with existing infrastructure and services in the whole resort. Training of the staff and providing all the needed support as per SLA contract. ",
        client: "Sun Gardens Dubrovnik",
        location: "Dubrovnik, Croatia",
        surface: "220.000 m²",
        value: "€630.000",
        finished: "April 2017.",
        contractor: "Procodex d.o.o.",
        url: "/pcx-projects/sun-gardens-croatia.jpg",
    },
    {
        name:"Kempinski Hotel",
        about: "Design, configuring and commissioning of new LAN, Wireless LAN and IPTV systems. Integration of old and new IP backbone systems, supporting all relevant services in the hotel. ",
        client: "Kempinski Hotel Adriatic Istria",
        location: "Istria, Croatia",
        surface: "67.000 m²",
        value: "€147.000",
        finished: "February 2019.",
        contractor: "Procodex d.o.o.", 
        url: "/pcx-projects/kempinski-croatia.jpg",
    },
    {
        name:"Mama Shelter Hotel", 
        about: "Design, configuring and commissioning of new LAN and Wireless LAN systems. IP backbone system supports all relevant services in the hotel: IPTV, front office, back office, guest WiFi, Video-on-demand, etc.",
        client: "Mama Shelter Belgrade",
        location: "Belgrade, Serbia",
        surface: "7.200 m²",
        value: "€80.000",
        finished: "March 2018.",
        contractor: "Procodex d.o.o.",
        url: "/pcx-projects/mama-shelter_belgrade.jpg",
    },
    {
        name:"Belgrade Waterfront",
        about: "Project design, installing, configuring and commissioning of videointercom system. Training of the staff and providing all the needed support as per SLA contract.",
        client: "Belgrade Waterfront Residences",
        location: "Belgrade, Serbia",
        surface: "68.000 m2",
        value: "€40.000",
        finished: "September 2019.",
        contractor: "Procodex d.o.o.", 
        url: "/pcx-projects/belgrade_waterfront.jpg",
    },
    {
        name:"Marriott Hotel", 
        about: "Project design, installing, configuring and commissioning of LAN & WLAN, IPTV infotainment, fire alarm system and telephony. IP backbone system supports all relevant services in the hotel. ",
        client: "Courtyard Belgrade City Center",
        location: "Belgrade, Serbia",
        surface: "7.000 m²",
        value: "€230.000",
        finished: "October 2015",
        contractor: "Procodex d.o.o.",
        url: "/pcx-projects/marriot-belgrade.jpg",
    }
];

export default {projects};
